name: Build LaTeX Document
on: [push] # The Trigger (Step 2)

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/operating_systems.tex
            src/economy_and_social_change.tex

      - name: Compile XeLaTeX documents (Hebrew)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/logic_for_cs.tex
          latexmk_use_xelatex: true
          pre_compile: fc-cache -fv

      - name: Upload PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          include_files: |
            operating_systems.pdf
            economy_and_social_change.pdf
            logic_for_cs.pdf
            index.html